name: Deploy to AWS S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' # Specify the Node.js version here

    - name: Reorganize Files for Deployment
      run: |
        mkdir -p deployment/assets
        mkdir -p deployment/code
        cp -r assets/* deployment/assets/
        cp -r code/frontend/* deployment/code/
        cp code/frontend/index.html deployment/
        cp code/frontend/error.html deployment/

    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --follow-symlinks --delete --exclude '*' --include 'deployment/**'
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
